import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="AI Diabetes Risk Screening",
    page_icon="🩺",
    layout="wide"
)

@st.cache_resource
def load_model():
    return joblib.load("diabetes_model.pkl")

model = load_model()

st.title("🩺 AI Diabetes Risk Screening")

st.write(
    "Enter the health information below to generate a "
    "machine-learning screening risk score."
)

st.warning(
    "This tool is for educational and screening purposes only. "
    "It does not diagnose diabetes."
)

st.divider()

col1, col2 = st.columns(2)

with col1:

    high_bp = st.selectbox(
        "High Blood Pressure",
        ["No", "Yes"]
    )

    high_chol = st.selectbox(
        "High Cholesterol",
        ["No", "Yes"]
    )

    chol_check = st.selectbox(
        "Cholesterol Check in Last 5 Years",
        ["No", "Yes"]
    )

    bmi = st.number_input(
        "BMI",
        min_value=10.0,
        max_value=70.0,
        value=25.0
    )

    smoker = st.selectbox(
        "Smoked at least 100 cigarettes in your life",
        ["No", "Yes"]
    )

    stroke = st.selectbox(
        "History of Stroke",
        ["No", "Yes"]
    )

    heart_disease = st.selectbox(
        "Heart Disease or Heart Attack",
        ["No", "Yes"]
    )

    physical_activity = st.selectbox(
        "Physical Activity",
        ["No", "Yes"]
    )

    fruits = st.selectbox(
        "Consumes Fruit Daily",
        ["No", "Yes"]
    )

    veggies = st.selectbox(
        "Consumes Vegetables Daily",
        ["No", "Yes"]
    )

with col2:

    heavy_alcohol = st.selectbox(
        "Heavy Alcohol Consumption",
        ["No", "Yes"]
    )

    healthcare = st.selectbox(
        "Has Healthcare Coverage",
        ["No", "Yes"]
    )

    no_doc_cost = st.selectbox(
        "Could Not See Doctor Because of Cost",
        ["No", "Yes"]
    )

    gen_health = st.slider(
        "General Health (1 = Excellent, 5 = Poor)",
        1,
        5,
        3
    )

    mental_health = st.slider(
        "Poor Mental Health Days (Last 30 Days)",
        0,
        30,
        0
    )

    physical_health = st.slider(
        "Poor Physical Health Days (Last 30 Days)",
        0,
        30,
        0
    )

    difficulty_walking = st.selectbox(
        "Difficulty Walking",
        ["No", "Yes"]
    )

    sex = st.selectbox(
        "Sex",
        ["Female", "Male"]
    )

    age = st.slider(
        "Age Category (1–13)",
        1,
        13,
        5
    )

    education = st.slider(
        "Education Level (1–6)",
        1,
        6,
        4
    )

    income = st.slider(
        "Income Level (1–8)",
        1,
        8,
        5
    )

yes_no = {
    "No": 0,
    "Yes": 1
}

if st.button(
    "Check Diabetes Risk",
    type="primary",
    use_container_width=True
):

    input_data = pd.DataFrame([{

        "HighBP": yes_no[high_bp],

        "HighChol": yes_no[high_chol],

        "CholCheck": yes_no[chol_check],

        "BMI": bmi,

        "Smoker": yes_no[smoker],

        "Stroke": yes_no[stroke],

        "HeartDiseaseorAttack": yes_no[heart_disease],

        "PhysActivity": yes_no[physical_activity],

        "Fruits": yes_no[fruits],

        "Veggies": yes_no[veggies],

        "HvyAlcoholConsump": yes_no[heavy_alcohol],

        "AnyHealthcare": yes_no[healthcare],

        "NoDocbcCost": yes_no[no_doc_cost],

        "GenHlth": gen_health,

        "MentHlth": mental_health,

        "PhysHlth": physical_health,

        "DiffWalk": yes_no[difficulty_walking],

        "Sex": 1 if sex == "Male" else 0,

        "Age": age,

        "Education": education,

        "Income": income

    }])

    probability = model.predict_proba(input_data)[0][1]

    risk_score = probability * 100

    st.divider()

    st.subheader("Screening Result")

    st.metric(
        "Model Risk Score",
        f"{risk_score:.1f}%"
    )

    if probability >= 0.35:

        st.error(
            "Higher screening risk detected."
        )

        st.write(
            "The model score exceeded the screening "
            "threshold of 35%."
        )

    else:

        st.success(
            "Lower screening risk detected."
        )

        st.write(
            "The model score was below the screening "
            "threshold of 35%."
        )

    st.progress(float(probability))

    st.caption(
        "This result is generated by a machine-learning model "
        "trained using BRFSS public health data and should not "
        "be interpreted as a medical diagnosis."
    )